# .

In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

import numpy as np

In [2]:
x = np.random.randn(10,1,28,28)
x.shape

(10, 1, 28, 28)

In [3]:
print(x[0].shape)
print(x[1].shape)
x[0][0]

(1, 28, 28)
(1, 28, 28)


array([[-1.06757742e+00,  2.26310074e-01,  3.76196306e-01,
         1.05956572e+00,  1.22044950e+00,  4.29445091e-01,
        -3.07637963e-01,  8.90224209e-02,  7.55487425e-01,
         4.98588169e-01, -3.14209526e-01,  6.22694376e-01,
        -1.05137811e+00, -5.02030719e-02,  1.16503283e+00,
         5.23051067e-01, -1.23598917e+00, -3.84308984e-01,
         1.23338810e+00,  9.40115278e-02, -3.62293055e-01,
         2.67203513e-01, -7.31411424e-01, -8.21777656e-01,
         6.32269789e-02,  7.81262072e-01, -1.25337953e+00,
        -4.10461422e-01],
       [-2.87523172e+00,  1.40813764e+00, -6.39506697e-01,
        -3.20294461e-01,  1.51792934e-02, -4.71662160e-01,
        -5.20938138e-02,  2.85584176e-01,  1.94936115e-01,
        -8.04974980e-01,  3.19168439e-01,  5.27854338e-01,
         2.77999794e-01,  3.38389509e-01,  9.23808956e-01,
         9.33124050e-01,  1.43973608e-01,  4.27656542e-01,
         3.82991756e-01,  2.12387052e+00, -2.75042333e-01,
        -4.97227868e-02, -1.55

In [4]:
## test

import sys, os
sys.path.append(os.pardir+'/..')
from common.util import im2col
import random

print(dir(np.random))

# x1 = np.random.rand(1,1,3,3) #(data cnt, channel cnt, H, W)
x1 = np.random.randint(0,10, size=(2,2,4,4)) #(data cnt, channel cnt, H, W)
col1 = im2col(x1, 2, 2, stride=1, pad=0)
print(col1.shape)

print(x1)
print(col1)

# x2 = np.random.rand(10,3,7,7)  #(data cnt, channel cnt, H, W)
# col2 = im2col(x2, 5, 5, stride=1, pad=0)
# print(col2.shape)

['Lock', 'RandomState', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'absolute_import', 'beta', 'binomial', 'bytes', 'chisquare', 'choice', 'dirichlet', 'division', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'np', 'operator', 'pareto', 'permutation', 'poisson', 'power', 'print_function', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'warnings', 'weibull', 'zipf']
(18, 8)
[[[[3 0 7 4]
   [7 0 4 6]
   [6 8 9 5]
   [8 8 7 3]]

  [[5 3 6 6]
   [1 5 

In [5]:
import sys, os
sys.path.append(os.pardir+'/..')
from common.util import im2col
import random

x1 = np.random.rand(1,3,7,7) #(data cnt, channel cnt, H, W)
col1 = im2col(x1, 5, 5, stride=1, pad=0)
print(col1.shape)

x2 = np.random.rand(10,3,7,7)  #(data cnt, channel cnt, H, W)
col2 = im2col(x2, 5, 5, stride=1, pad=0)
print(col2.shape)



(9, 75)
(90, 75)


In [6]:
class Convolution:
    def __init__(self, W, b, stride=1, pad=0):
        self.W = W
        self.b = b
        self.stride = stride
        self.pad = pad
        
    def forward(self, x):
        FN, C, FH, FW = self.W.shape
        N, C, H, W = x.shape
        
        print("init shape:", self.W.shape, x.shape)
        
        out_h = int(1 + (H + 2*self.pad - FH) / self.stride)
        out_w = int(1 + (W + 2*self.pad - FW) / self.stride)
        
        col = im2col(x, FH, FW, self.stride, self.pad)
        col_W = self.W.reshape(FN, -1).T
        
#         print("col shape:", col.shape, "col_W shape: ", col_W.shape)
        
        out = np.dot(col, col_W) + self.b
        
        print("out_h:", out_h, "out_w:", out_w)
        
        print(out.shape)
        print(out.reshape(N, out_h, out_w, -1).shape)
        out = out.reshape(N, out_h, out_w, -1).transpose(0, 3, 1, 2)
        
        print(out.shape)
        
        
        return out
        

In [7]:
x = np.random.rand(1,3,7,7)
b = np.random.rand(1)
f = np.random.rand(2,3,2,2)

a = Convolution(f,b, 1, 0)
a.forward(x)

init shape: (2, 3, 2, 2) (1, 3, 7, 7)
out_h: 6 out_w: 6
(36, 2)
(1, 6, 6, 2)
(1, 2, 6, 6)


array([[[[2.80891748, 3.45479384, 3.45208055, 3.81019155, 2.73170288,
          2.27255805],
         [3.39694796, 3.50421565, 3.32522892, 3.50159679, 3.28064049,
          3.01867736],
         [2.64558138, 3.39641942, 3.10682346, 2.87718274, 2.92371392,
          3.68928911],
         [2.51439575, 3.052007  , 3.55091592, 2.22640469, 2.87174276,
          4.10935994],
         [2.94060901, 2.76501702, 2.72031735, 2.7830363 , 2.58743516,
          3.49481856],
         [2.79307706, 2.80306372, 2.67473274, 2.47249938, 3.61533773,
          3.46697349]],

        [[3.11531484, 3.30252826, 3.93744348, 3.4909321 , 3.5613043 ,
          2.81890612],
         [3.65060864, 3.85058908, 3.74660177, 3.68666841, 3.83989616,
          3.28016735],
         [3.31287954, 3.47797559, 4.55979155, 2.80125222, 3.78662646,
          4.47987371],
         [2.63157028, 3.47441692, 3.42191294, 2.84180208, 3.94362581,
          4.56376869],
         [3.24043808, 3.09762416, 3.19627038, 2.74415488, 3.23578478

In [8]:
class Pooling:
    def __init__(self, pool_h, pool_w, stride=1, pad=0):
        self.pool_h = pool_h
        self.pool_w = pool_w
        self.stride = stride
        self.pad = pad
        
    def forward(self, x):
        N, C, H, W = x.shape
        out_h = int(1 + ( H - self.pool_h ) / self.stride )
        out_w = int(1 + ( W - self.pool_w ) / self.stride )
        
        print(x)
        
        # make col
        col = im2col(x, self.pool_h, self.pool_w, self.stride, self.pad)  # 채널을 포함해서 전재
        print("col(ori): \n", col)
        col = col.reshape(-1, self.pool_h*self.pool_w)  # 채널도 분리해서 전개
        print("col: \n", col)
        
        # maxium value
        out = np.max(col, axis=1)
        print("out: \n", out.reshape(out.shape[0], -1))
        
        #
        out = out.reshape(N, out_h, out_w, C).transpose(0,3,1,2)
        
        return out
        

In [9]:
# x = np.random.rand(1,3,4,4)
x = np.random.randint(0,10, size=(1,2,4,4))

ap = Pooling(2, 2, 2, 0)
ap.forward(x)


[[[[6 4 5 6]
   [5 1 8 4]
   [1 5 8 9]
   [2 0 6 6]]

  [[2 4 4 3]
   [7 8 4 2]
   [5 6 0 5]
   [9 4 4 7]]]]
col(ori): 
 [[6. 4. 5. 1. 2. 4. 7. 8.]
 [5. 6. 8. 4. 4. 3. 4. 2.]
 [1. 5. 2. 0. 5. 6. 9. 4.]
 [8. 9. 6. 6. 0. 5. 4. 7.]]
col: 
 [[6. 4. 5. 1.]
 [2. 4. 7. 8.]
 [5. 6. 8. 4.]
 [4. 3. 4. 2.]
 [1. 5. 2. 0.]
 [5. 6. 9. 4.]
 [8. 9. 6. 6.]
 [0. 5. 4. 7.]]
out: 
 [[6.]
 [8.]
 [8.]
 [4.]
 [5.]
 [9.]
 [9.]
 [7.]]


array([[[[6., 8.],
         [5., 9.]],

        [[8., 4.],
         [9., 7.]]]])

In [10]:
class Relu:
    def __init__(self):
        self.mask = None
        
    def forward(self, x):
        self.mask = (x <= 0)
        out = x.copy()
        out[self.mask] = 0
        
        return out
    
    def backward(self, dout):
        dout[self.mask] = 0
        dx = dout
        return dx

In [15]:
from common.layers import *
import collections 

class SimpleConvNet:
    def __init__(self, input_dim=(1, 28, 28), 
                 conv_param={'filter_num':30, 'filter_size':5, 'pad':0, 'stride':1},
                 hidden_size=100, output_size=10, weight_init_std=0.01 ):
        filter_num = conv_param['filter_num']
        filter_size = conv_param['filter_size']
        filter_pad = conv_param['pad']
        filter_stride = conv_param['stride']
        input_size = input_dim[1] # ????? 왜 1번째껄 뺴지??
        conv_output_size = (input_size - filter_size + 2*filter_pad) / filter_stride + 1
        pool_output_size = int(filter_num * (conv_output_size/2) * (conv_output_size/2))  # ??? size 산정을 어떻게 한거지?
        
        self.params = {}
        self.params['W1'] = weight_init_std * np.random.randn(filter_num, input_dim[0], filter_size, filter_size)
        self.params['b1'] = np.zeros(filter_num)
        self.params['W2'] = weight_init_std * np.random.randn(pool_output_size, hidden_size)
        self.params['b2'] = np.zeros(hidden_size)
        self.params['W3'] = weight_init_std * np.random.randn(hidden_size, output_size)
        self.params['b3'] = np.zeros(output_size)
        
        self.layers = collections.OrderedDict()
        self.layers['Conv1'] = Convolution(self.params['W1'],
                                           self.params['b1'],
                                           conv_param['stride'],
                                           conv_param['pad'])
        self.layers['Relu1'] = Relu()
        self.layers['Pool1'] = Pooling(pool_h=2, pool_w=2, stride=2)
        self.layers['Affine1'] = Affine(self.params['W2'],
                                        self.params['b2'])
        self.layers['Relu2'] = Relu()
        self.layers['Affine2'] = Affine(self.params['W3'],
                                        self.params['b3'])
        
        self.last_layer = SoftmaxWithLoss()




In [16]:
a = SimpleConvNet((1,4,4), {'filter_num':2, 'filter_size':5, 'pad':0, 'stride':1 }, hidden_size=100, output_size=10, weight_init_std=0.01 )


In [ ]:
class Convolution:
    def __init__(self, W, b, stride=1, pad=0):
        self.W = W
        self.b = b
        self.stride = stride
        self.pad = pad
        
    def forward(self, x):
        FN, C, FH, FW = self.W.shape
        N, C, H, W = x.shape
        
        print("init shape:", self.W.shape, x.shape)
        
        out_h = int(1 + (H + 2*self.pad - FH) / self.stride)
        out_w = int(1 + (W + 2*self.pad - FW) / self.stride)
        
        col = im2col(x, FH, FW, self.stride, self.pad)
        col_W = self.W.reshape(FN, -1).T
        
#         print("col shape:", col.shape, "col_W shape: ", col_W.shape)
        
        out = np.dot(col, col_W) + self.b
        
        print("out_h:", out_h, "out_w:", out_w)
        
        print(out.shape)
        print(out.reshape(N, out_h, out_w, -1).shape)
        out = out.reshape(N, out_h, out_w, -1).transpose(0, 3, 1, 2)
        
        print(out.shape)
        
        
        return out