# .

In [10]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

import numpy as np

In [9]:
x = np.random.randn(10,1,28,28)
x.shape

(10, 1, 28, 28)

In [15]:
print(x[0].shape)
print(x[1].shape)
x[0][0]

(1, 28, 28)
(1, 28, 28)


array([[-3.82584324e-01, -1.11989728e-02,  2.48045997e-01,
         8.67575741e-03,  2.55187524e-01, -1.95546043e+00,
        -4.18614935e-01, -5.25682886e-02, -3.90086096e-01,
        -1.84807520e+00,  1.24456284e-01,  1.46562516e+00,
         6.88086064e-01, -7.78818589e-01, -8.54377043e-01,
         5.48464404e-01, -1.43601827e+00, -3.52777807e-01,
         9.82219464e-01, -6.24559865e-01,  1.43099109e+00,
        -2.86619103e-01, -9.52867090e-01,  4.35351291e-01,
         1.26982863e-02,  9.63155660e-01, -1.22572431e+00,
         6.82186940e-01],
       [-2.33324659e-01,  9.84680287e-01,  1.13653443e+00,
         8.67936044e-01,  2.23838098e+00,  5.20878627e-01,
         5.09306259e-01, -9.26536008e-01,  5.55089899e-01,
         1.17394656e-01,  2.61423316e-01, -1.02115462e+00,
        -8.75478378e-01, -3.57263268e-01, -1.30588071e+00,
         1.15332081e+00, -6.34136277e-01,  1.31274658e+00,
        -4.65481527e-01,  1.22279539e+00,  5.14401814e-01,
        -2.47818088e-01,  2.17

In [47]:
## test

import sys, os
sys.path.append(os.pardir+'/..')
from common.util import im2col
import random

print(dir(np.random))

# x1 = np.random.rand(1,1,3,3) #(data cnt, channel cnt, H, W)
x1 = np.random.randint(0,10, size=(2,2,4,4)) #(data cnt, channel cnt, H, W)
col1 = im2col(x1, 2, 2, stride=1, pad=0)
print(col1.shape)

print(x1)
print(col1)

# x2 = np.random.rand(10,3,7,7)  #(data cnt, channel cnt, H, W)
# col2 = im2col(x2, 5, 5, stride=1, pad=0)
# print(col2.shape)

['Lock', 'RandomState', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'absolute_import', 'beta', 'binomial', 'bytes', 'chisquare', 'choice', 'dirichlet', 'division', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'np', 'operator', 'pareto', 'permutation', 'poisson', 'power', 'print_function', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'warnings', 'weibull', 'zipf']
(18, 8)
[[[[1 2 5 2]
   [3 1 6 0]
   [9 0 5 4]
   [7 8 7 0]]

  [[3 5 4 2]
   [0 8 

In [52]:
import sys, os
sys.path.append(os.pardir+'/..')
from common.util import im2col
import random

x1 = np.random.rand(1,3,7,7) #(data cnt, channel cnt, H, W)
col1 = im2col(x1, 5, 5, stride=1, pad=0)
print(col1.shape)

x2 = np.random.rand(10,3,7,7)  #(data cnt, channel cnt, H, W)
col2 = im2col(x2, 5, 5, stride=1, pad=0)
print(col2.shape)



(9, 75)
(90, 75)


In [80]:
class Convolution:
    def __init__(self, W, b, stride=1, pad=0):
        self.W = W
        self.b = b
        self.stride = stride
        self.pad = pad
        
    def forward(self, x):
        FN, C, FH, FW = self.W.shape
        N, C, H, W = x.shape
        
        print("init shape:", self.W.shape, x.shape)
        
        out_h = int(1 + (H + 2*self.pad - FH) / self.stride)
        out_w = int(1 + (W + 2*self.pad - FW) / self.stride)
        
        col = im2col(x, FH, FW, self.stride, self.pad)
        col_W = self.W.reshape(FN, -1).T
        
#         print("col shape:", col.shape, "col_W shape: ", col_W.shape)
        
        out = np.dot(col, col_W) + self.b
        
        print("out_h:", out_h, "out_w:", out_w)
        
        print(out.shape)
        print(out.reshape(N, out_h, out_w, -1).shape)
        out = out.reshape(N, out_h, out_w, -1).transpose(0, 3, 1, 2)
        
        print(out.shape)
        
        
        return out
        

In [88]:
x = np.random.rand(1,3,7,7)
b = np.random.rand(1)
f = np.random.rand(2,3,2,2)

a = Convolution(f,b, 1, 0)
a.forward(x)

init shape: (2, 3, 2, 2) (1, 3, 7, 7)
out_h: 6 out_w: 6
(36, 2)
(1, 6, 6, 2)
(1, 2, 6, 6)


array([[[[3.54934639, 2.9178157 , 4.04181625, 4.35746127, 3.35270228,
          2.53102323],
         [2.88433006, 3.12450265, 4.64755083, 4.55378468, 3.35237078,
          3.71225905],
         [3.32854228, 3.51714945, 4.05575177, 3.93905311, 3.81445261,
          2.97426895],
         [2.75573535, 3.55908246, 4.54721191, 3.53106577, 3.16319865,
          2.63729521],
         [3.24975087, 3.6951497 , 3.55185762, 4.31252864, 3.64320775,
          3.18271818],
         [4.11259078, 3.87395504, 3.67255206, 4.64851685, 4.04596279,
          2.69149038]],

        [[2.70155004, 2.0285113 , 2.64544678, 3.83806451, 2.28715827,
          2.72481594],
         [1.74222412, 2.21623642, 3.33406078, 2.79805339, 2.50415158,
          2.19633251],
         [2.54738491, 2.62528472, 3.00632556, 3.40170517, 2.74247463,
          3.0600477 ],
         [2.52178173, 2.73746381, 2.36450981, 2.32033578, 2.37265045,
          2.34234668],
         [2.39008699, 2.08810214, 3.47455362, 2.81968207, 2.63522813